include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - prefer_relative_imports
    - directives_ordering
    - prefer_const_constructors

analyzer:
  errors:
    invalid_use_of_visible_for_testing_member: error

formatter:
  trailing_commas: preserve
  page_width: 120
