name: kite
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  cached_network_image: ^3.4.1
  collection: ^1.19.1
  flutter:
    sdk: flutter
  flutter_html: ^3.0.0
  flutter_svg: ^2.0.17
  fuzzywuzzy: ^1.2.0
  http: ^1.3.0
  intl: ^0.20.2
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.4.5
  build_runner: ^2.4.15

flutter:
  assets:
    - assets/test/bay.json
    - assets/test/business.json
    - assets/test/cryptocurrency.json
    - assets/test/gaming.json
    - assets/test/kite.json
    - assets/test/onthisday.json
    - assets/test/tech.json
    - assets/test/serbia.json
    - "assets/test/the netherlands.json"
    - "assets/test/linux & oss.json"
    - assets/test/science.json
    - assets/test/sports.json
    - assets/test/world.json
    - assets/test/usa.json
    - assets/test/romania.json
    - assets/img/kite.svg
    - assets/img/kite-dark.svg
    - assets/img/dark-theme.svg
    - assets/img/image-placeholder.svg

